### ISSUE TITLE
Duplicate attachments in eForms

### ISSUE THREAD

**Issue by jw098** [cortico-health/oscar-enhancement-suite#224]
In eForms, every time you open and close the Cortico widget, it attaches a duplicate of the current eForm to be emailed to the patient.

I tried sending a test message to my own email, and I can confirm that I received multiple links to the same eForm.

Desired behavior: Previously attached eForms should be cleared and only the current eForm should be attached. I feel that attached documents and files should not be cleared, however.

Attached screenshot:
![image](https://user-images.githubusercontent.com/28998963/202100664-fba1342d-cc04-4fd3-a972-84de495a0503.png)

**Comment by countable** [comment]
@dimdejesus FYI ^

@jw098 thanks for the heads up

**Comment by eusahn** [comment]
Fixed, should be released in the next cycle.

Thank you @jw098
